import Vue from "vue";
import VueI18n from "vue-i18n";

Vue.use(VueI18n);

const messages = {


    /* English language
     *****************/
    en: {
        app_name: 'RTI REPLAYS',
        nav: {
            logout: "Logout"
        },
        home: {
            // Menu
            my_list: "My List",
            home: "HOME",
            play: "Play",
            movies: "MOVIES",
            series: "SHOWS",
            kids: "KIDS",
            tv: "LIVE TV",
            browser: 'Browser',
            collection: 'MY COLLECTION',
            movies_category: 'Movies',
            // Trending
            trending: "Trending",
            year: "Year",
            rating: "Rating",
            likes: "Likes",
            recenlty_watched: 'Continue Watching...',
            // Genre
            genre: "Genre",
            all: "All",
            action: "Action",
            adventure: "Adventure",
            animation: "Animation",
            biography: "Biography",
            comedy: "Comedy",
            crime: "Crime",
            documentary: "Documentary",
            drama: "Drama",
            family: "Family",
            fantasy: "Fantasy",
            history: "History",
            horror: "Horror",
            music: "Music",
            mystery: "Mystery",
            romance: "Romance",
            sci_fi: "Sci-Fi",
            sport: "Sport",
            thriller: "Thriller",
            war: "War",
            sorry_no_result: "SORRY NO RESULT WERE FOUND",
            search: "Search",
            filmography: "filmography",
            // new
            what_is_new: "Latest News",
            featured_show: 'Featured Shows',
            featured_latest_episode: 'Latest Episodes',
            recommendation_series: 'Recommended Shows',
            recommendation_movies: 'Recommended Movies',
            popular_series: 'Popular Shows',
            popular_movies: 'Popular Movies',
            watch_now: 'Watch Now',
            subscribe: 'Subscription',

        },
        setting: {
            user_setting: "User Settings",
            biling: "Billing",
            app_setting: "App setting",
            language: "Language",
            profile: "Profile",
            security: "Security",
            update_payment: "Update payment",
            billing_details: "Billing details",
            change_plan: "Change plan",
            viewing_history: "Viewing history",
            description: "Description",
            next_plan: "Next months plan",
            start_period: "Start period",
            end_period: "End period",
            total: "Total",
            update_profile_picture: "Update Profile Picture",
            name: "Name",
            mail: "E-mail",
            successful_update: "Successful update",
            update: "Update",
            current: "Current",
            password: "Password",
            password_confirm: "Re-enter password ",
            credit_card_or_debit: "Credit card or debit",
            cancel_your_memebrship: "Cancel your membership",
            resume_your_memebrship: "Resume your membership",
            cancel_memebrship: "Cancel membership",
            resume_memebrship: "Resume membership",
            cancel_note: "Cancellation will be effective at the end of your current billing",
            change_streaming_plan: "Change Streaming Plan",
            select_language: "Select language",
            adjust_subtitles: "Adjust captions",
            email_already: "Email has already been taken",
            watch_date: 'Date watched',

            support: "Support Inbox",
            submit_request: "Submit Request",
            submit: 'Submit',
            cancel: 'Cancel',
            open: 'Open',
            close: 'Close',
            status: 'Status',
            subject: 'Subject',
            date: 'Date',
            support_desc: 'Provide a detailed description',
            support_tell: 'Tell us what your enquiry is about',
            reply: 'Send Reply',

            device_activity: 'Device Activity',
            security_message_header: "Please Re-enter Your Password",
            security_message_body: "For your security, you must re-enter your password to continue",
            font_size: "Font Size",
            font_weight: "Font Weight",
            font_color: "Font color",
            font_backgrond: "Background color"

        },

        register: {
            login: "Login",
            signup: "Signup",
            forget_password: "Forget your password ?",
            create_accont: "Don't have an account?",
            agree_role: "By clicking on Sign up, you agree to",
            and: "and",
            stepone: "Just one step!",
            steptwo: "Just two more steps and you're done!",
            payment: "Payment",
            payment_message: "Set up your payment",
            support: "Support",
            choose_plan: "Choose Plan",
            change_plan: "Change Plan",
            choose_plan_message: "Choose a plan that's right for you",
            cancel_anytime: "No commitments, Cancel online at anytime",
            day_free: "Day free",
            loading: "Loading",
            password_reset: "Password Reset",
            password_message: "Please enter your email address, We'll send you an email with a link to reset your password",
            password_help: "If you still need help, contact",
            start_membership: "START MEMBERSHIP",
            finish: "Finish",
            continue: "Continue",
            welcome_to: "Welcome To",
            your: "Your ",
            message_one: "membership, which begins with a free trial",
            cancel_before: "Cancel anytime before",
            message_two: "and will not be charged, to cancel go to your account setting  and Cancel Membership",
            account_details: "Your account details",
            payment_info: "Payment Information",
            discover: "Home",
            privacy: "Privacy",
            aboutus: "About us",
            contactus: "Contact us",

            // signup
            im_male: "I'm male",
            im_female: "I'm female",

            // subscribe
            sub_title: 'Personalize your experience',
            sub_desc: "Start following shows you like and never miss a new episode. Don't forget to pick your favourite movie genres as well, so that we cloud recommand new release to you. Once your're done with your selections on this page, we'll take you to your presonalized My Suvscriptions page, with recommendations of shows and movies tailored your taste and preferences.",
            sub_note: "Select which genres do you like and we'll automatically recommend movies you might like.",
            sub_following: 'Following',
            sub_follow: 'Follow',
            sub_button: "COMPLETE REGISTRATION"
        },

        show: {
            summary: "Summary",
            edit: "Edit",
            delete: "Delete",
            season: "Season ",
            episode: "Episode",
            cast: "Cast",
            trailer: 'Trailer',
            recommendation_movie: 'Recommended Movies',
            recommendation_series: 'Recommended Shows',
            like: 'Like',
            no_series: 'Coming soon',
            my_collection: 'My Collection',
            soon: "SOON",

        },
        footer: {
            faq: "faq",
            privacy: "Privacy Policy",
            terms: "Terms Of Service",
            contactus: "Contact Us",
            aboutus: "About Us",
            phone_number: "Phone number",
            first_name: "First name",
            last_name: "Last name",
            email: "E-mail",
            message: "Message",
            address: "address",
            tryanothertime: "Try another time",
            success_send: "Successfully sent, we will contact you soon"
        },
        report: {
            what_happening: "What's Happening",
            labeling_problem: "Labeling Problem",
            video_problem: "Video Problem",
            sound_problem: "Sound Problem",
            caption_problem: "Captions Problem",
            more_details: "More Details ?",
            send: "SEND",
        },

        player: {
            geo_message: 'This content is not available in your country',
            login_message: 'To continue watching please login'
        }
    },


    /* France language
     *****************/
    fr: {
        app_name: 'RTI REPLAYS',

        nav: {
            logout: "Déconnection"
        },
        home: {
            // Menu
            my_list: "Ma playliste",
            home: "Acceuil",
            play: "Jouer",
            movies: "Films",
            series: "Séries",
            kids: "Enfants",
            tv: "TV en Direct",
            browser: 'Navigateur',
            collection: 'Ma Sélection',
            movies_category: 'Films',
            // Trending
            trending: "Tendance",
            year: "Année",
            rating: "évaluation",
            likes: "J'aimes",
            recenlty_watched: 'Récement vue',
            // Genre
            genre: "Genre", // new
            all: "Tous",
            action: "Action",
            adventure: "Aventure",
            animation: "Animation",
            biography: "Biographie",
            comedy: "Comédie",
            crime: "Crime",
            documentary: "Documentaire",
            drama: "Drame",
            family: "Famille",
            fantasy: "Fantasy",
            history: "Histoire",
            horror: "Horreur",
            music: "Musique",
            mystery: "Mystère",
            romance: "Romance",
            sci_fi: "Sci-Fi",
            sport: "Sport",
            thriller: "Thriller",
            war: "Guerre",
            sorry_no_result: "Désolé, aucun résultat n'a ete trouvé",
            search: "Recherche",

            // new
            what_is_new: "Derniers Journaux",
            featured_show: 'Emission à la Une',
            featured_latest_episode: 'Derniers épisodes',
            recommendation_series: 'Emissions Recommendées',
            recommendation_movies: 'Films Recommendées',
            popular_series: 'Emissions Populaires',
            popular_movies: 'Films Populaires',
            watch_now: 'Voir la Vidéo',
            subscribe: 'Abonnement',

        },
        setting: {
            // Setting
            user_setting: "Paramètres utilisateur",
            biling: "Facturation",
            app_setting: "Paramètre d'application",
            language: "La langue",
            profile: "Profile",
            security: "Securité",
            update_payment: "Mettre à  jour votre payment",
            billing_details: "Détails de Facturation",
            change_plan: "Changer de plan",
            viewing_history: "Affichage de l'historique",
            description: "La description",
            next_plan: "Plan des prochains mois",
            start_period: "Période de démarrage",
            end_period: "Période de fin",
            total: "Totale",
            update_profile_picture: "Mettre à jour votre photo de profile",
            name: "prénom",
            mail: "Messagerie",
            successful_update: "Mise à  jour réussie",
            update: 'Mettre à  jour',
            current: "Actuel",
            password: "Mot de passe",
            password_confirm: "Confirmer le mot de passe",
            credit_card_or_debit: "Carte de crédit ou débit",
            cancel_your_memebrship: "Annulez votre abonement",
            resume_your_memebrship: "Reactivez votre abonement",
            cancel_memebrship: "Annuler votre abonement",
            resume_memebrship: "Reprendre votre abonement",
            cancel_note: "L 'annulation sera effective à la fin de votre facturation actuelle",
            change_streaming_plan: "Modifier le plan de streaming",
            select_language: "Choisir la langue",
            adjust_subtitles: "Ajuster les sous-titres",
            email_already: "Cet e-mail existe déja",
            watch_date: 'Date de lecture',

            support: "Boite de support technique",
            submit_request: "Envoyer la demande",
            submit: 'Soumettre',
            cancel: 'Annuler',
            open: 'Ouvrir',
            close: 'Fermer',
            status: 'Statut',
            subject: 'Sujet',
            date: 'Rendez-vous amoureux',
            support_desc: 'Fournir une description détaillée',
            support_tell: 'Dites-nous ce que votre demande concerne',
            reply: 'Envoyer une réponse',

            device_activity: 'Activité de votre appareil',

            security_message_header: "Veuillez re-taper votre mot de passe",
            security_message_body: "Pour votre sécurité, vous devez ressaisir votre mot de passe pour continuer",
            font_size: "Taille de police",
            font_weight: "Poids de la police",
            font_color: "Couleur de la police",
            font_backgrond: "Couleur de fond"

        },
        register: {
            login: "S'identifier",
            signup: "S'inscrire",
            forget_password: "Mot de passe oublié?",
            create_accont: "Vous n'avez pas de compte?",
            agree_role: "En cliquant sur S'inscrire, vous acceptez de",
            and: "et",
            stepone: "Juste un pas!",
            steptwo: "Juste deux étapes de plus et vous avez terminé!",
            payment: "Paiement",
            payment_message: "Configurez votre paiement",
            support: "Support technique",
            choose_plan: "Choisir plan",
            change_plan: "Changez de Plan",
            choose_plan_message: "Choisissez un plan qui vous convient",
            cancel_anytime: "Aucun engagement, Annuler en ligne à tout moment",
            day_free: "Jour libre",
            loading: "Chargement",
            password_reset: "Réinitialiser le mot de passe",
            password_message: "Veuillez entrer votre adresse e-mail, nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe",
            password_help: "Si vous avez toujours besoin d'aide, contactez",
            start_membership: "DEMARREZ VOTRE ABONEMENT",
            finish: "terminer",
            continue: "Continuer",
            welcome_to: "Bienvenue à ",
            your: "Votre ",
            message_one: "adhésion, qui commence par un essai gratuit",
            cancel_before: "Annulez à  tout moment avant",
            message_two: "et ne sera pas facturé, pour annuler aller sur vos paramètres de compte et annuler l'adhésion",
            account_details: "Les détails de votre compte",
            payment_info: "Informations de paiement",
            discover: "Découvrir",
            privacy: "Confidentialité",
            aboutus: "à propos de nous",
            contactus: "Contactez nous",
            // signup
            im_male: "Je suis un Homme",
            im_female: "Je suis une femme",

            // subscribe
            sub_title: 'Personalizez votre experience!',
            sub_desc: "Cela nous permettra de vous proposer vos programmes préférés en un clic et de vous en faire découvrir de nouveaux, choisis spécialement pour vous.",
            sub_note: "Sélectionnez les genres que vous aimez et nous vous recommanderons automatiquement les films ou émissions que vous pourriez aimer.",
            sub_following: 'Suivi',
            sub_follow: 'Suivre',
            sub_button: "COMPLETEZ VOTRE INSCRIPTION"

        },

        show: {
            summary: "Résumé",
            edit: "Modifier",
            delete: "Supprimer",
            season: "Saison ",
            cast: "Fonte",
            recommendation_movie: 'Films Recommendées',
            recommendation_series: 'Emissions Recommendées',
            trailer: 'Bande annonce',
            similar: 'Similaire',
            like: 'Comme',
            no_series: 'Bientôt en ligne',
            my_collection: 'Ma Sélection',
            soon: "bientôt",

        },
        footer: {
            faq: "faq",
            privacy: "Emplois",
            terms: "Conditions d'utilisation",
            contactus: "Contactez nous",
            aboutus: "à propos de nous",
            phone_number: 'Numéro de téléphone',
            first_name: "Prénom",
            last_name: "Nom de famille",
            email: "E-mail",
            message: "Message",
            address: "Adresse",
            tryanothertime: "Essayez dans un autre temps",
            success_send: "Envoi réussi, nous vous contacterons bientôt"
        },
        report: {
            what_happening: " Que se passe-t-il?",
            labeling_problem: "Problème de label",
            video_problem: "Problème de vidéo",
            sound_problem: "Problème de son",
            caption_problem: "Problème de sous-titrage",
            more_details: "Plus de détails ?",
            send: "ENVOYER",
        },
        player: {
            geo_message: "Ce contenu n'est pas disponible dans votre pays",
            login_message: 'Pour continuer à regarder, veuillez vous connecter'
        }
    },


};
// Create VueI18n instance with options
export default new VueI18n({
    locale: "en",
    fallbackLocale: 'en',
    messages,
    silentFallbackWarn: true
})

